### ISSUE TITLE
Ratatui.rs Widget Showcase

### ISSUE THREAD

**Issue by joshka** [benjajaja/ratatui-image#11]
Hey there,
I'm putting together a widget showcase page at https://ratatui.rs/showcase/third-party-widgets/ and would like to add this widget. The demo right now seems a bit complex to use as it shows all the possible features. Would you be interested in creating a simpler demo that just shows the main aspect in a small area like the examples we have on the site already?

If you have a good simple demo, I'm happy to create the actual GIF. The process is fairly simple though, so if you want to help, see https://github.com/ratatui-org/website/tree/main/code/widget-showcase-third-party for more info.

**Comment by benjajaja** [comment]
@joshka sadly, sixel support is not working with VHS https://github.com/charmbracelet/vhs/issues/43 I also tested locally and the image is not included in the resulting .gif.

There is in fact a simple `screenshot` demo, which I was trying to use for some automated testing (that never was quite fruitful):
[image-link](https://github.com/benjajaja/ratatui-image/blob/master/assets/test_screenshot.png)

Is that good enough? If not, I can make a different .gif, just manually instead of VHS.

**Comment by joshka** [comment]
Bummer on VHS not supporting it :/

Yeah, the screenshot demo is good enough for the showcase. I'll use that.

**Comment by joshka** [comment]
https://github.com/ratatui-org/website/pull/341
