### ISSUE TITLE
Support transparent background of images

### ISSUE THREAD

**Issue by Ktrod** [benjajaja/ratatui-image#15]
Support RGBA for image backgrounds instead of just RGB.

**Comment by benjajaja** [comment]
Ratatui works in "immediate mode". The area covered by the image cannot be cleared, it must be set to be skipped instead, so that nothing draws over the image in the same render pass. Thus, if we would allow for transparency, artifacts of some previous render would be visible.

![image](https://github.com/benjajaja/ratatui-image/assets/310215/6c3aa83f-8470-43f3-aa1c-08febb936755)

**Comment by benjajaja** [comment]
Also, icy_sixel does not seem to support transparency at the moment.
