### ISSUE TITLE
Include the ThreadImage widget in the crate

### ISSUE THREAD

**Issue by josueBarretogit** [benjajaja/ratatui-image#25]
Looking at the `async` example I wonder why the crate does not provide the `ThreadImage` widget and the `ThreadProtocol`,  at the moment if different applications want to use  that approach of rendering images the widget would have to be reimplemented over and over again

**Comment by benjajaja** [comment]
I didn't do it initially because I didn't want to also provide several async implementation. However you are right, there is no reason to not to export the thread widgets!

@josueBarretogit published as v1.0.3, available as `thread` module: https://docs.rs/ratatui-image/1.0.3/ratatui_image/thread/index.html
